### ISSUE TITLE
Epic: Simplify wallet installation

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-kit#30]
I [just did a run-through](https://gist.github.com/justmoon/35fc2a06bcd8dd277addabfa880fbd11) of installing five-bells-wallet from scratch and suggest the following changes:
- [x] Remove notification signing keys in the ledger (interledgerjs/five-bells-ledger#338)
- [x] Not having to manually rebuild node-sass (35649d866245112db78a883ed1ded0cff92fda8a)
- [x] Not having to create upload folder
- [x] Provide only a single secret (and five-bells-wallet generates secrets for subcomponents from that)
- [x] Remove dependency on `expect` (#31)
- [x] Remove the need to manually create `wallet-ledger` database in postgres (#23)
- [x] Remove the need to run with `LEDGER_DB_SYNC` to initialize ledger database (interledgerjs/five-bells-ledger#339)
- [x] Unify connector with other configuration (`connector.list` vs env variables)
- [x] Rename to ilp-connector-kit (#33)

**Comment by emschwartz** [comment]
How about adding a docker image for the wallet?

**Comment by emschwartz** [comment]
Also it would be helpful if the default behavior for the `configure` command was to output to a file that would be automatically found and parsed by the app, instead of having to run with an unusual command like `sh -ac '. ./config.list ; npm start'` (as is currently recommended by the `ilp-kit-cli`)

**Comment by vhpoet** [comment]
@emschwartz

**Comment by justmoon** [comment]
> Also it would be helpful if the default behavior for the configure command was to output to a file that would be automatically found and parsed by the app

But make sure that the file is optional, i.e. it still starts and uses the configuration from the environment if the file doesn't exist.

**Comment by vhpoet** [comment]
@emschwartz your second request is implemented in https://github.com/interledgerjs/ilp-kit/commit/61163c5ba2fd5a0ace2d4424fece3b27626a5a32
