### ISSUE TITLE
v4 todo

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-kit#464]
- [x] integration tests
- [ ] docker
- [x] apidoc
- [x] circle
- [ ] pm2
- [x] docs
- [x] ilp-kit-cli usage
- [x] an optional node web server
- [x] optional node web server docs
